In [1]:
import pandas as pd

# Read CSV file
df = pd.read_csv(r"D:\Main Flow Internship\example.csv")

# View the first few rows
print(df.head())

# Get basic statistics
print(df.describe())

# Select a column
age_column = df['Age']
print(age_column)

# Filter rows where Salary is greater than 60000
high_salary_df = df[df['Salary'] > 60000]
print(high_salary_df)

# Add a new column for Bonus (10% of Salary)
df['Bonus'] = df['Salary'] * 0.1

# Drop the Gender column
df = df.drop('Gender', axis=1)

# Handle missing data (if any)
df = df.fillna(0)

# Save to a new CSV file
df.to_csv('modified_example.csv', index=False)

      Name  Age  Gender  Salary
0    Alice   30  Female   70000
1      Bob   25    Male   48000
2  Charlie   35    Male   54000
3    David   45    Male   65000
4      Eva   40  Female   71000
             Age       Salary
count  10.000000     10.00000
mean   34.300000  62000.00000
std     6.532823   9568.46673
min    25.000000  48000.00000
25%    29.250000  55000.00000
50%    33.500000  62500.00000
75%    39.500000  70750.00000
max    45.000000  73000.00000
0    30
1    25
2    35
3    45
4    40
5    29
6    32
7    28
8    38
9    41
Name: Age, dtype: int64
    Name  Age  Gender  Salary
0  Alice   30  Female   70000
3  David   45    Male   65000
4    Eva   40  Female   71000
6  Grace   32  Female   72000
9  Julia   41  Female   73000

In [5]:
import pandas as pd
import numpy as np

# Read CSV file
df = pd.read_csv(r"D:\Main Flow Internship\example.csv")

# Introduce missing values (for demonstration)
df.loc[2, 'Age'] = np.nan
df.loc[4, 'Salary'] = np.nan

# Introduce duplicate rows (for demonstration)
df = df.append(df.iloc[0], ignore_index=True)
df = df.append(df.iloc[2], ignore_index=True)

# Check for missing values
print("Missing values before cleaning:")
print(df.isnull().sum())

# Fill missing values
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())

# Check for missing values after cleaning
print("Missing values after cleaning:")
print(df.isnull().sum())

# Check for duplicate rows
print("Duplicates before removing:")
print(df.duplicated().sum())

# Remove duplicate rows
df_cleaned = df.drop_duplicates()

# Check for duplicate rows after cleaning
print("Duplicates after removing:")
print(df_cleaned.duplicated().sum())

# Display the cleaned DataFrame
print(df_cleaned)

# Save the cleaned DataFrame to a new CSV file
df_cleaned.to_csv('cleaned_example.csv', index=False)

Missing values before cleaning:
Name      0
Age       2
Gender    0
Salary    1
dtype: int64
Missing values after cleaning:
Name      0
Age       0
Gender    0
Salary    0
dtype: int64
Duplicates before removing:
2
Duplicates after removing:
0
      Name   Age  Gender        Salary
0    Alice  30.0  Female  70000.000000
1      Bob  25.0    Male  48000.000000
2  Charlie  33.8    Male  54000.000000
3    David  45.0    Male  65000.000000
4      Eva  40.0  Female  61181.818182
5    Frank  29.0    Male  58000.000000
6    Grace  32.0  Female  72000.000000
7   Hannah  28.0  Female  49000.000000
8     Ivan  38.0    Male  60000.000000
9    Julia  41.0  Female  73000.000000

C:\Users\shubh\AppData\Local\Temp\ipykernel_23772\260827826.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(df.iloc[0], ignore_index=True)
C:\Users\shubh\AppData\Local\Temp\ipykernel_23772\260827826.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(df.iloc[2], ignore_index=True)

In [6]:
import pandas as pd

# Read CSV file
df = pd.read_csv(r"D:\Main Flow Internship\example.csv")

# Display the original DataFrame
print("Original DataFrame:")
print(df)

# Filtering Data
filtered_df = df[df['Age'] > 30]
print("\nFiltered DataFrame (Age > 30):")
print(filtered_df)

# Sorting Data
sorted_df = df.sort_values(by='Salary', ascending=False)
print("\nSorted DataFrame (by Salary, descending):")
print(sorted_df)

# Grouping Data
grouped_df = df.groupby('Gender')['Salary'].mean().reset_index()
print("\nGrouped DataFrame (mean Salary by Gender):")
print(grouped_df)

Original DataFrame:
      Name  Age  Gender  Salary
0    Alice   30  Female   70000
1      Bob   25    Male   48000
2  Charlie   35    Male   54000
3    David   45    Male   65000
4      Eva   40  Female   71000
5    Frank   29    Male   58000
6    Grace   32  Female   72000
7   Hannah   28  Female   49000
8     Ivan   38    Male   60000
9    Julia   41  Female   73000

Filtered DataFrame (Age > 30):
      Name  Age  Gender  Salary
2  Charlie   35    Male   54000
3    David   45    Male   65000
4      Eva   40  Female   71000
6    Grace   32  Female   72000
8     Ivan   38    Male   60000
9    Julia   41  Female   73000

Sorted DataFrame (by Salary, descending):
      Name  Age  Gender  Salary
9    Julia   41  Female   73000
6    Grace   32  Female   72000
4      Eva   40  Female   71000
0    Alice   30  Female   70000
3    David   45    Male   65000
8     Ivan   38    Male   60000
5    Frank   29    Male   58000
2  Charlie   35    Male   54000
7   Hannah   28  Female   49000
1      Bob   25    Male   48000

Grouped DataFrame (mean Salary by Gender):
   Gender   Salary
0  Female  67000.0
1    Male  57000.0